"""블로그 서비스 프로토콜"""

from typing import Protocol

from app.models.blog import BlogPost
from app.schemas.blog import BlogPostCreate, BlogPostUpdate


class BlogServiceProtocol(Protocol):
    def list_published(self, tag: str | None, page: int, size: int) -> list[BlogPost]: ...
    def list_all(self) -> list[BlogPost]: ...
    def get_published(self, slug: str) -> BlogPost: ...
    def get_any(self, slug: str) -> BlogPost: ...
    def create(self, data: BlogPostCreate) -> BlogPost: ...
    def update(self, slug: str, data: BlogPostUpdate) -> BlogPost: ...
    def delete(self, slug: str) -> None: ...
    def increment_view(self, slug: str) -> int: ...
